<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/

$config['base_url'] = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$config['base_url'] .= "://".$_SERVER['HTTP_HOST'];
$config['base_url'] .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'REST_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '/home/taqdaredu.com/logs/ci/';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 86400;//10 days
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 1800;
$config['sess_regenerate_destroy'] = TRUE;
$config['sess_match_useragent'] = FALSE;
$config['sess_expire_on_close'] = FALSE;
$config['same_site'] = null;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? TRUE : FALSE);
$config['cookie_httponly'] = TRUE;


//Auto Logout
// $config['cookie_prefix']	= 'academy';
// $config['cookie_domain']	= 'client domain name';
// $config['cookie_path']		= '/';
// $config['cookie_secure']	= TRUE;
// $config['cookie_httponly'] 	= TRUE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = TRUE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
|
| ---------------------------------------------------------------------------
| SECURITY REVIEW 2026-08-02 -- why csrf_protection is still FALSE
| ---------------------------------------------------------------------------
| CI3 CSRF works only if EVERY POST body carries $config['csrf_token_name'].
| A survey of application/views showed:
|   * 232 hand written "<form ... method=post>" tags vs. only 2 form_open()
|     calls in the whole code base -> CI can auto inject the hidden field in
|     2 forms out of 234.
|   * 82 jQuery $.post()/$.ajax() call sites, of which only 7 view files emit
|     $this->security->get_csrf_hash() (the DataTables screens).
|   * 168 admin view files / 158 Admin controller methods depend on those.
| Flipping this flag to TRUE without first patching those views returns HTTP
| 403 "The action you have requested is not allowed" on virtually every admin
| save/delete/AJAX call, i.e. it takes the whole back office down. The views
| belong to other maintainers, so they were not touched here.
|
| What was done instead (see tq_auth_* helpers at the bottom of this file):
|   * every authentication related POST in controllers/Login.php now runs
|     tq_auth_verify_origin(), an Origin/Referer same-site check, which stops
|     cross-site login / registration / password-reset CSRF without needing a
|     token in the HTML.
| To finish the job later: add
|     <input type="hidden" name="<?php echo $this->security->get_csrf_token_name(); ?>"
|            value="<?php echo $this->security->get_csrf_hash(); ?>">
| to the 232 forms (or convert them to form_open()), add the same pair to the
| 82 AJAX payloads, then set csrf_protection = TRUE. The exclude list below is
| already filled in with the endpoints that must stay token free (mobile API
| + payment gateway webhooks), so only the flag needs flipping afterwards.
| csrf_regenerate was set to FALSE (it is inert while protection is off) so
| that parallel AJAX calls do not invalidate each other once it is enabled.
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = FALSE;
// Entries are treated as regular expressions by CI_Security::csrf_verify().
$config['csrf_exclude_uris'] = array(
	'api/.*',                 // mobile app REST endpoints (token auth, no cookies)
	'apis/.*',
	'payment/.*',             // gateway callbacks / IPN / webhooks
	'addons/.*/webhook.*',
	'home/sendEmailToAssignedAddresses',
	'.*/ajax_.*',
	'.*_ajax',
);

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';

/*
|==========================================================================
| tq_auth_* : shared authentication hardening helpers (security review 2026-08-02)
|--------------------------------------------------------------------------
| This file is loaded by CI before every other component, so the helpers
| below are guaranteed to exist for controllers, models and helpers alike.
| They are plain functions (no side effects at load time) and every one of
| them is wrapped in function_exists() so a double require cannot fatal.
|
| Storage: users.password (existing column, varchar(255)) plus the two new
| tables tq_auth_login_attempts and tq_auth_password_resets.
|==========================================================================
*/

if ( ! function_exists('tq_auth_db'))
{
	/**
	 * Returns the shared CI database object, loading it when needed.
	 * Returns NULL when called outside of a CI request (e.g. CLI bootstrap).
	 */
	function tq_auth_db()
	{
		if ( ! function_exists('get_instance'))
		{
			return NULL;
		}
		$CI =& get_instance();
		if ( ! is_object($CI))
		{
			return NULL;
		}
		if ( ! isset($CI->db) OR ! is_object($CI->db))
		{
			@$CI->load->database();
		}
		return (isset($CI->db) && is_object($CI->db)) ? $CI->db : NULL;
	}
}

if ( ! function_exists('tq_auth_ip'))
{
	function tq_auth_ip()
	{
		if (function_exists('get_instance'))
		{
			$CI =& get_instance();
			if (is_object($CI) && isset($CI->input))
			{
				$ip = $CI->input->ip_address();
				if ( ! empty($ip))
				{
					return $ip;
				}
			}
		}
		return isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '0.0.0.0';
	}
}

/* ----------------------------------------------------------------------
 * 1) Password hashing : password_hash() with transparent sha1 migration
 * -------------------------------------------------------------------- */

if ( ! function_exists('tq_password_is_legacy'))
{
	/** TRUE for the old unsalted sha1() digests (40 hex chars). */
	function tq_password_is_legacy($stored)
	{
		return (is_string($stored) && strlen($stored) === 40 && ctype_xdigit($stored));
	}
}

if ( ! function_exists('tq_password_hash'))
{
	function tq_password_hash($plain)
	{
		return password_hash((string) $plain, PASSWORD_DEFAULT);
	}
}

if ( ! function_exists('tq_password_matches'))
{
	/**
	 * Constant time check of a plain password against whatever is stored:
	 * a modern password_hash() digest, a legacy sha1() digest, or (defensively)
	 * a plain text value left over from an old import.
	 */
	function tq_password_matches($plain, $stored)
	{
		if ( ! is_string($stored) OR $stored === '' OR $plain === NULL OR $plain === '')
		{
			return FALSE;
		}
		if (tq_password_is_legacy($stored))
		{
			return hash_equals($stored, sha1((string) $plain));
		}
		if ($stored[0] === '$')
		{
			return password_verify((string) $plain, $stored);
		}
		return hash_equals($stored, (string) $plain);
	}
}

if ( ! function_exists('tq_password_needs_upgrade'))
{
	function tq_password_needs_upgrade($stored)
	{
		if ( ! is_string($stored) OR $stored === '')
		{
			return TRUE;
		}
		if ($stored[0] !== '$')
		{
			return TRUE; // sha1 or plain text
		}
		return password_needs_rehash($stored, PASSWORD_DEFAULT);
	}
}

if ( ! function_exists('tq_password_upgrade'))
{
	/**
	 * Progressive migration: called right after a SUCCESSFUL verification.
	 * Re-hashes the password with password_hash() and stores it. Never called
	 * on a failed login, so no existing account can be invalidated.
	 */
	function tq_password_upgrade($user_id, $plain, $stored)
	{
		if (empty($user_id) OR $plain === NULL OR $plain === '' OR ! tq_password_needs_upgrade($stored))
		{
			return FALSE;
		}
		$db = tq_auth_db();
		if ($db === NULL)
		{
			return FALSE;
		}
		$db->where('id', $user_id);
		$db->update('users', array('password' => tq_password_hash($plain)));
		return TRUE;
	}
}

if ( ! function_exists('tq_password_authenticate'))
{
	/**
	 * Verify + auto-upgrade in one call.
	 * $user is an array or object row coming from the users table.
	 */
	function tq_password_authenticate($user, $plain)
	{
		if (empty($user))
		{
			return FALSE;
		}
		$user = (array) $user;
		if ( ! isset($user['password']))
		{
			return FALSE;
		}
		if ( ! tq_password_matches($plain, $user['password']))
		{
			return FALSE;
		}
		if (isset($user['id']))
		{
			tq_password_upgrade($user['id'], $plain, $user['password']);
		}
		return TRUE;
	}
}

/* ----------------------------------------------------------------------
 * 2) Brute force throttling  (table: tq_auth_login_attempts)
 * -------------------------------------------------------------------- */

if ( ! defined('TQ_AUTH_WINDOW'))        define('TQ_AUTH_WINDOW', 900);   // 15 minutes
if ( ! defined('TQ_AUTH_MAX_PER_USER'))  define('TQ_AUTH_MAX_PER_USER', 5);
if ( ! defined('TQ_AUTH_MAX_PER_IP'))    define('TQ_AUTH_MAX_PER_IP', 25);

if ( ! function_exists('tq_auth_gc'))
{
	function tq_auth_gc()
	{
		if (mt_rand(1, 50) !== 1)
		{
			return;
		}
		$db = tq_auth_db();
		if ($db === NULL)
		{
			return;
		}
		$db->where('attempted_at <', time() - 86400)->delete('tq_auth_login_attempts');
		$db->where('expires_at <', time() - 86400)->delete('tq_auth_password_resets');
	}
}

if ( ! function_exists('tq_auth_record_failure'))
{
	function tq_auth_record_failure($identifier, $scope = 'login')
	{
		$db = tq_auth_db();
		if ($db === NULL)
		{
			return;
		}
		$db->insert('tq_auth_login_attempts', array(
			'identifier'   => substr(strtolower(trim((string) $identifier)), 0, 191),
			'ip'           => substr(tq_auth_ip(), 0, 45),
			'scope'        => substr($scope, 0, 32),
			'attempted_at' => time(),
		));
		tq_auth_gc();
	}
}

if ( ! function_exists('tq_auth_clear_failures'))
{
	function tq_auth_clear_failures($identifier, $scope = 'login')
	{
		$db = tq_auth_db();
		if ($db === NULL)
		{
			return;
		}
		$db->where('scope', $scope)
		   ->where('identifier', substr(strtolower(trim((string) $identifier)), 0, 191))
		   ->where('ip', substr(tq_auth_ip(), 0, 45))
		   ->delete('tq_auth_login_attempts');
	}
}

if ( ! function_exists('tq_auth_failure_count'))
{
	function tq_auth_failure_count($identifier = NULL, $scope = 'login', $by_ip_only = FALSE)
	{
		$db = tq_auth_db();
		if ($db === NULL)
		{
			return 0;
		}
		$db->where('scope', $scope)->where('attempted_at >=', time() - TQ_AUTH_WINDOW);
		if ($by_ip_only)
		{
			$db->where('ip', substr(tq_auth_ip(), 0, 45));
		}
		else
		{
			$db->where('identifier', substr(strtolower(trim((string) $identifier)), 0, 191));
			$db->where('ip', substr(tq_auth_ip(), 0, 45));
		}
		return (int) $db->count_all_results('tq_auth_login_attempts');
	}
}

if ( ! function_exists('tq_auth_is_throttled'))
{
	/**
	 * TRUE when this (identifier, ip) pair burned TQ_AUTH_MAX_PER_USER tries,
	 * or when this IP alone burned TQ_AUTH_MAX_PER_IP tries, inside the window.
	 */
	function tq_auth_is_throttled($identifier, $scope = 'login')
	{
		if (tq_auth_failure_count($identifier, $scope) >= TQ_AUTH_MAX_PER_USER)
		{
			return TRUE;
		}
		return (tq_auth_failure_count(NULL, $scope, TRUE) >= TQ_AUTH_MAX_PER_IP);
	}
}

if ( ! function_exists('tq_auth_throttle_message'))
{
	function tq_auth_throttle_message()
	{
		$minutes = (int) ceil(TQ_AUTH_WINDOW / 60);
		return 'Too many failed attempts. Please try again in ' . $minutes . ' minutes.'
			. ' / تم تجاوز عدد المحاولات المسموح به، برجاء المحاولة بعد ' . $minutes . ' دقيقة.';
	}
}

/* ----------------------------------------------------------------------
 * 3) Password reset tokens  (table: tq_auth_password_resets)
 *    32 random bytes -> 64 hex chars, stored hashed, single use, 15 min TTL.
 * -------------------------------------------------------------------- */

if ( ! defined('TQ_AUTH_RESET_TTL')) define('TQ_AUTH_RESET_TTL', 900); // 15 minutes

if ( ! function_exists('tq_auth_reset_fingerprint'))
{
	function tq_auth_reset_fingerprint($token)
	{
		return hash('sha256', (string) $token);
	}
}

if ( ! function_exists('tq_auth_create_reset_token'))
{
	/**
	 * Issues a fresh single use reset token for $email and voids the previous
	 * unused ones. Returns the raw token (to be emailed) or FALSE.
	 */
	function tq_auth_create_reset_token($email)
	{
		$db = tq_auth_db();
		if ($db === NULL OR empty($email))
		{
			return FALSE;
		}
		$user = $db->get_where('users', array('email' => $email))->row_array();
		if (empty($user))
		{
			return FALSE;
		}
		// void any pending token for this account
		$db->where('email', $email)->where('used_at IS NULL', NULL, FALSE)
		   ->update('tq_auth_password_resets', array('used_at' => time()));

		$token = bin2hex(random_bytes(32));
		$now   = time();
		$db->insert('tq_auth_password_resets', array(
			'user_id'    => $user['id'],
			'email'      => $email,
			'token_hash' => tq_auth_reset_fingerprint($token),
			'created_at' => $now,
			'expires_at' => $now + TQ_AUTH_RESET_TTL,
			'used_at'    => NULL,
			'ip'         => substr(tq_auth_ip(), 0, 45),
		));
		return $token;
	}
}

if ( ! function_exists('tq_auth_find_reset_token'))
{
	/** Returns the reset row when the token is valid, unused and unexpired. */
	function tq_auth_find_reset_token($token)
	{
		$db = tq_auth_db();
		if ($db === NULL OR ! is_string($token) OR strlen($token) !== 64 OR ! ctype_xdigit($token))
		{
			return FALSE;
		}
		$row = $db->get_where('tq_auth_password_resets', array(
			'token_hash' => tq_auth_reset_fingerprint($token),
		))->row_array();

		if (empty($row) OR $row['used_at'] !== NULL OR (int) $row['expires_at'] < time())
		{
			return FALSE;
		}
		return $row;
	}
}

if ( ! function_exists('tq_auth_consume_reset_token'))
{
	/**
	 * Atomically burns the token (UPDATE ... WHERE used_at IS NULL) so a
	 * replayed link cannot change the password a second time.
	 * Returns the reset row on success, FALSE otherwise.
	 */
	function tq_auth_consume_reset_token($token)
	{
		$row = tq_auth_find_reset_token($token);
		if ($row === FALSE)
		{
			return FALSE;
		}
		$db = tq_auth_db();
		$db->where('id', $row['id'])
		   ->where('used_at IS NULL', NULL, FALSE)
		   ->update('tq_auth_password_resets', array('used_at' => time()));

		return ($db->affected_rows() === 1) ? $row : FALSE;
	}
}

/* ----------------------------------------------------------------------
 * 4) Same site check for authentication POSTs (CSRF mitigation that does
 *    not need a hidden token in the HTML). See the CSRF note above.
 * -------------------------------------------------------------------- */

if ( ! function_exists('tq_auth_verify_origin'))
{
	/**
	 * TRUE when the request is not a POST, when no Origin/Referer was sent
	 * (non browser client), or when the sent origin host equals the host the
	 * request was addressed to. FALSE only on a genuine cross-site POST.
	 */
	function tq_auth_verify_origin()
	{
		if ( ! isset($_SERVER['REQUEST_METHOD']) OR strtoupper($_SERVER['REQUEST_METHOD']) !== 'POST')
		{
			return TRUE;
		}
		$target = isset($_SERVER['HTTP_HOST']) ? strtolower($_SERVER['HTTP_HOST']) : '';
		if ($target === '')
		{
			return TRUE;
		}
		$source = '';
		if ( ! empty($_SERVER['HTTP_ORIGIN']))
		{
			$source = $_SERVER['HTTP_ORIGIN'];
		}
		elseif ( ! empty($_SERVER['HTTP_REFERER']))
		{
			$source = $_SERVER['HTTP_REFERER'];
		}
		if ($source === '' OR $source === 'null')
		{
			return TRUE; // curl / mobile app / privacy proxy: nothing to compare
		}
		$host = parse_url($source, PHP_URL_HOST);
		if (empty($host))
		{
			return TRUE;
		}
		$port = parse_url($source, PHP_URL_PORT);
		$host = strtolower($host) . ($port ? ':' . $port : '');

		return ($host === $target OR $host === preg_replace('/:\d+$/', '', $target));
	}
}
